# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-05 07:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import config.mixins


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=120, verbose_name='Image Title')),
                ('description', models.CharField(blank=True, max_length=120, verbose_name='Image Description')),
                ('image', models.ImageField(upload_to='img/gallery/%Y/%m', verbose_name='Image')),
            ],
            options={
                'verbose_name_plural': 'Gallery Images',
                'verbose_name': 'Gallery Image',
            },
        ),
        migrations.CreateModel(
            name='ListingIndexModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_title', models.CharField(help_text='The displayed title of the Listing Index Page', max_length=120, verbose_name='Listing Index Page Title')),
                ('slug', models.SlugField(help_text='Listing Index Page Title as it appears in the url', max_length=120, verbose_name='Listing Index Page Slug')),
                ('meta_title', models.CharField(help_text='Very important for SEO. Include Keywords', max_length=120, verbose_name='Listing Index page Meta Title')),
                ('meta_description', models.CharField(help_text='Very important for SEO. Include keywords', max_length=255, verbose_name='Listing Index Page Meta Description')),
                ('order_by', models.CharField(choices=[('date_available', 'Date Available'), ('date_published', 'Date Posted'), ('price', 'Listing Price')], default='date_available', max_length=120, verbose_name='Order Listings By')),
            ],
            options={
                'verbose_name_plural': 'Listing Index Page Settings',
                'verbose_name': 'Listing Index Page Settings',
            },
            bases=(config.mixins.SingleInstanceMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ListingModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Listing Street Address', max_length=255, verbose_name='Listing Name')),
                ('slug', models.SlugField(help_text='Listing name as it appears in the url', verbose_name='Listing Slug')),
                ('meta_title', models.CharField(help_text='A Title with Keywords for SEO', max_length=120, verbose_name='Meta Title')),
                ('meta_description', models.CharField(help_text='A Description for SEO purposes', max_length=255, verbose_name='Meta Description')),
                ('main_image', models.ImageField(help_text='Primary Image for the listing', upload_to='img/listings/%Y/%m', verbose_name='Featured Image')),
                ('date_published', models.DateField(auto_now_add=True, verbose_name='Date Posted')),
                ('date_available', models.DateField(blank=True, verbose_name='Date Available')),
                ('is_sold', models.BooleanField(default=False, help_text='Check this box if the property has been sold', verbose_name='Is Sold?')),
                ('date_sold', models.DateField(blank=True, help_text='The date the property was sold', verbose_name='Date Sold')),
                ('price', models.IntegerField(blank=True, verbose_name='Listing Price')),
                ('location', models.CharField(help_text='Full Address of the property', max_length=255, verbose_name='Listing Location')),
                ('property_description', models.TextField(help_text='A description of the home/apartment', verbose_name='Property Description')),
                ('neighborhood_description', models.TextField(help_text='A description of the property neighborhood', verbose_name='Neighborhood Description')),
            ],
            options={
                'verbose_name_plural': 'Listings',
                'verbose_name': 'Listing',
            },
        ),
        migrations.AddField(
            model_name='galleryimage',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_image', to='listings.ListingModel'),
        ),
    ]
