# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-09 07:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_auto_20151205_0720'),
    ]

    operations = [
        migrations.AddField(
            model_name='listingindexmodel',
            name='page_description',
            field=models.TextField(blank=True, help_text='Describe the listings. HTML ok.', verbose_name='Page Description'),
        ),
    ]
