# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-06 03:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItemModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The display name of the menu item', max_length=80, verbose_name='Menu Item Name')),
                ('link', models.URLField(blank=True, help_text='Where the menu item will link to.', verbose_name='Link')),
            ],
            options={
                'verbose_name_plural': 'Menu Items',
                'verbose_name': 'Menu Item',
            },
        ),
        migrations.CreateModel(
            name='MenuModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of the menu', max_length=120, verbose_name='Menu Name')),
                ('slug', models.SlugField()),
            ],
            options={
                'verbose_name_plural': 'Menus',
                'verbose_name': 'Menu',
            },
        ),
        migrations.AddField(
            model_name='menuitemmodel',
            name='menu',
            field=models.ForeignKey(help_text='The menu this item will be a part of.', on_delete=django.db.models.deletion.CASCADE, related_name='menu_item', to='menus.MenuModel', verbose_name='Parent Menu'),
        ),
    ]
