# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-05 19:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContentPageModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Page Title as it appears on the page.', max_length=255, verbose_name='Page Title')),
                ('slug', models.SlugField(help_text='The Page name as it appears in the url.', verbose_name='Page slug')),
                ('published', models.DateTimeField(auto_now=True, help_text='The date the page is published.', verbose_name='Page Published')),
                ('status', models.BooleanField(default=True, help_text='Check this box to make the page available to the public.', verbose_name='Page is live')),
                ('meta_title', models.CharField(help_text='Very important for SEO. Include keywords.', max_length=120, verbose_name='Page Meta Title')),
                ('meta_description', models.CharField(help_text='Very important for SEO. Include keywords.', max_length=255, verbose_name='Page Meta Description')),
                ('body', models.TextField()),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(db_index=True, editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='pages.ContentPageModel', verbose_name='Parent Page')),
            ],
            options={
                'verbose_name_plural': 'Content Pages',
                'verbose_name': 'Content Page',
            },
            managers=[
                ('_default_manager', django.db.models.manager.Manager()),
            ],
        ),
    ]
